Fix/ledger integration
Zilliqa/neo-savant pull request #122
Opened 2021-08-27 06:22 UTC by micovi

This PR replaces Ledger Transport U2F and Ledger Transport WebAuthn in favor of WebUSB to fix Ledger Devices connections on newest Chromium browsers.

2021-09-05 23:28 UTC, noel-yoo requested changes

2021-09-05 23:28 UTC, noel-yoo commented on package.json
>      "@ledgerhq/hw-transport-webauthn": "^5.15.0",
Remove the unused dependencies:
```
"@ledgerhq/hw-transport-u2f": "^5.13.1",
"@ledgerhq/hw-transport-webauthn": "^5.15.0",
```

2021-09-08 02:57 UTC, bb111189 commented
> This PR replaces Ledger Transport U2F and Ledger Transport WebAuthn in favor of WebUSB to fix Ledger Devices connections on newest Chromium browsers.

Can WebUSB work on FF? I remember we need to use U2F on FF and WebUSB on chromium based browsers

2021-09-08 03:00 UTC, noel-yoo commented
check this https://caniuse.com/?search=WebUSB @bb111189

2021-09-08 04:00 UTC, bb111189 commented
> check this https://caniuse.com/?search=WebUSB @bb111189

Yes. I think for FF user agents, we need to stick to U2F. The rest, we can use WebUSB

2021-09-14 09:28 UTC, micovi commented on package.json
>      "@ledgerhq/hw-transport-webauthn": "^5.15.0",
Removed the webauthn dep

2021-09-14 09:30 UTC, micovi commented
Added a check if there is WebUSB supported then fallback to U2F for FF browsers.
Removed webauthn dep.
Also added the check on Import account.

2021-09-15 05:43 UTC, noel-yoo approved these changes

2021-09-17 07:36 UTC, merged